version: '3'
tasks:
  build-all:
    cmds:
      - task clean
      - task build-darwin
  build:
    vars:
      platform: linux
      architecture: amd64
    cmds:
      - rm scratch/emballm || true
      - GOARCH={{.architecture}} GOOS={{.platform}} go build -o scratch/emballm main.go
  clean:
    cmds:
      - rm -rf build/dist
  docker-build-gar:
    vars:
      platform: linux
      architecture: amd64
    cmds:
      - task build
      - pkill Ollama || true
      - pkill ollama || true
      - OLLAMA_MODELS=$PWD/scratch/models ollama pull gemma:2b
      - OLLAMA_MODELS=$PWD/scratch/models ollama pull gemma:7b
      - DOCKER_DEFAULT_PLATFORM={{.platform}}/{{.architecture}} docker build --no-cache -t us-east1-docker.pkg.dev/sto-play/sto-private/emballm-runner:latest .
  docker-run-local:
    vars:
      platform: linux
      architecture: amd64
    cmds:
      - DOCKER_DEFAULT_PLATFORM={{.platform}}/{{.architecture}} docker run -it -v $PWD/scratch/harness:/harness -v $PWD/scratch/addon:/addon  us-east1-docker.pkg.dev/sto-play/sto-private/emballm-runner:latest
  make-scratch:
    cmds:
    - mkdir -p scratch
    - cd scratch && git clone https://github.com/fportantier/vulpy.git ./harness