version: '3'
tasks:
  build-all:
    cmds:
      - task clean
      - task build-darwin
      - task build-linux
      - task build-windows
  clean:
    cmds:
      - rm -r build/dist
  build-darwin:
    cmds:
      - mkdir -p build/darwin build/dist
      - GOARCH=amd64 GOOS=darwin go build -o build/darwin/emballm main.go
      - chmod +x build/darwin/emballm
      - cp build/emballm.yaml.example build/darwin/emballm.yaml
      - cd build/darwin && zip -r ../dist/darwin.zip . && cd ../..
      - rm -r build/darwin
  build-linux:
    cmds:
      - mkdir -p build/linux build/dist
      - GOARCH=amd64 GOOS=linux go build -o build/linux/emballm main.go
      - chmod +x build/linux/emballm
      - cp build/emballm.yaml.example build/linux/emballm.yaml
      - cd build/linux && zip -r ../dist/linux.zip . && cd ../..
      - rm -r build/linux
  build-windows:
    cmds:
      - mkdir -p build/windows build/dist
      - GOARCH=amd64 GOOS=windows go build -o build/windows/emballm.exe main.go
      - chmod +x build/windows/emballm.exe
      - cp build/emballm.yaml.example build/windows/emballm.yaml
      - cd build/windows && zip -r ../dist/windows.zip . && cd ../..
      - rm -r build/windows
