version: '3'
tasks:
  build-all:
    cmds:
      - task clean
      - task build-darwin
  build-darwin:
    vars:
      platform: darwin
    cmds:
      - mkdir -p build/{{.platform}} build/dist
      - GOARCH=amd64 GOOS={{.platform}} go build -o build/{{.platform}}/emballm main.go
      - chmod +x build/{{.platform}}/emballm
      - cd build/{{.platform}} && zip -r ../dist/{{.platform}}.zip . && cd ../..
      - rm -r build/{{.platform}}
  clean:
    cmds:
      - rm -rf build/dist
  docker-build:
    cmds:
      - docker build -t emballm-runner:latest .
  make-scratch:
    cmds:
    - mkdir -p scratch
    - cd scratch && git clone https://github.com/fportantier/vulpy.git ./harness